source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'Sense-UIButtons_Tests' do
  pod 'Sense-UIButtons', :path => '../'
  
  # Artsy stuff
  pod 'Sense-UIColors', :git => 'https://github.com/douglastaquary/Sense-UIColors.git', :branch => 'master'
  pod 'UIView+BooleanAnimations'
  
  pod 'Specta'
  pod 'Expecta'
end
